import os
import random
import re
import sys
import unittest
from math import gcd

repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)

from generators.cyclic_group_generator import CyclicGroupGenerator
from helpers import DELIM


ZN_RE = re.compile(
    r"Find the cyclic subgroup generated by (\d+) in Z_(\d+) under "
    r"addition modulo \d+\. Is it a generator of the group\?"
)
UNITS_RE = re.compile(
    r"Find the cyclic subgroup generated by (\d+) in U\((\d+)\) under "
    r"multiplication modulo \d+\. Is it a generator of the group\?"
)


def make_step(*parts):
    parts = [str(part) for part in parts]
    while parts and parts[-1] == "":
        parts.pop()
    return DELIM.join(parts)


def list_text(values):
    return ", ".join(str(value) for value in values)


def set_text(values):
    return "{" + list_text(values) + "}"


def units(n):
    return [value for value in range(1, n) if gcd(value, n) == 1]


def parse_problem(problem):
    match = ZN_RE.fullmatch(problem)
    if match:
        element, n = map(int, match.groups())
        return {"variant": "zn", "element": element, "n": n}
    match = UNITS_RE.fullmatch(problem)
    assert match is not None, problem
    element, n = map(int, match.groups())
    return {"variant": "units", "element": element, "n": n}


def expected_zn(n, element):
    group_size = n
    subgroup = [0]
    current = 0
    steps = [
        make_step("GROUP_SETUP", f"Z_{n}", "addition mod n",
                  f"group size {group_size}"),
        make_step("CYCLIC_START", element, "identity 0"),
    ]
    for k in range(1, n + 1):
        previous = current
        total = previous + element
        current = total % n
        steps.append(make_step("A", previous, element, total))
        steps.append(make_step("MOD_REDUCE", total, f"mod {n}", current))
        steps.append(make_step("SUBGROUP_ELEM", f"k={k}", current))
        if current == 0:
            break
        subgroup.append(current)
    verdict = "yes" if len(subgroup) == group_size else "no"
    steps.extend([
        make_step("CYCLIC_SUBGROUP", set_text(subgroup), len(subgroup)),
        make_step("CHECK", "subgroup size = group size", verdict),
    ])
    answer = f"<{element}> = {set_text(subgroup)}; generator = {verdict}"
    return steps, answer


def expected_units(n, element):
    elements = units(n)
    group_size = len(elements)
    subgroup = [1]
    current = 1
    steps = [
        make_step("GROUP_SETUP", f"U({n})", "multiplication mod n",
                  f"group size {group_size}"),
        make_step("CYCLIC_START", element, "identity 1"),
    ]
    for k in range(1, group_size + 1):
        previous = current
        product = previous * element
        current = product % n
        steps.append(make_step("M", previous, element, product))
        steps.append(make_step("MOD_REDUCE", product, f"mod {n}", current))
        steps.append(make_step("SUBGROUP_ELEM", f"k={k}", current))
        if current == 1:
            break
        subgroup.append(current)
    verdict = "yes" if len(subgroup) == group_size else "no"
    steps.extend([
        make_step("CYCLIC_SUBGROUP", set_text(subgroup), len(subgroup)),
        make_step("CHECK", "subgroup size = group size", verdict),
    ])
    answer = f"<{element}> = {set_text(subgroup)}; generator = {verdict}"
    return steps, answer


def expected_flow(example):
    parts = parse_problem(example["problem"])
    if parts["variant"] == "zn":
        steps, answer = expected_zn(parts["n"], parts["element"])
    else:
        steps, answer = expected_units(parts["n"], parts["element"])
    steps.append(make_step("Z", answer))
    return steps, answer


class TestCyclicGroupGenerator(unittest.TestCase):
    def setUp(self):
        random.seed(42)
        self.gen = CyclicGroupGenerator()

    def test_output_contract(self):
        result = self.gen.generate()
        for key in ("problem_id", "operation", "problem", "steps",
                    "final_answer"):
            self.assertIn(key, result)
        self.assertTrue(result["steps"][-1].startswith(f"Z{DELIM}"))
        self.assertEqual(result["steps"][-1].split(DELIM, 1)[1],
                         result["final_answer"])

    def test_oracle_reconstructs_full_trace_from_problem_text(self):
        for _ in range(500):
            result = self.gen.generate()
            expected_steps, answer = expected_flow(result)
            self.assertEqual(result["final_answer"], answer, result["problem"])
            self.assertEqual(result["steps"], expected_steps,
                             result["problem"])

    def test_arithmetic_steps(self):
        for _ in range(300):
            result = self.gen.generate()
            for raw_step in result["steps"]:
                fields = raw_step.split(DELIM)
                if fields[0] == "A":
                    self.assertEqual(int(fields[1]) + int(fields[2]),
                                     int(fields[3]), raw_step)
                elif fields[0] == "M":
                    self.assertEqual(int(fields[1]) * int(fields[2]),
                                     int(fields[3]), raw_step)
                elif fields[0] == "MOD_REDUCE":
                    mod = int(fields[2].split()[1])
                    self.assertEqual(int(fields[1]) % mod, int(fields[3]),
                                     raw_step)

    def test_variants_are_available(self):
        for variant in ("zn", "units"):
            gen = CyclicGroupGenerator(variant)
            for _ in range(50):
                result = gen.generate()
                self.assertEqual(result["operation"],
                                 f"cyclic_group_{variant}")
                self.assertEqual(parse_problem(result["problem"])["variant"],
                                 variant)

    def test_invalid_variant_rejected(self):
        with self.assertRaises(ValueError):
            CyclicGroupGenerator("bogus")

    def test_pipe_safe(self):
        for _ in range(300):
            result = self.gen.generate()
            for raw_step in result["steps"]:
                self.assertLessEqual(len(raw_step.split(DELIM)) - 1, 4,
                                     raw_step)
            self.assertNotIn(DELIM, result["final_answer"])


if __name__ == "__main__":
    unittest.main()
