import random
from math import gcd

from base_generator import ProblemGenerator
from helpers import step, jid


def list_text(values):
    return ", ".join(str(value) for value in values)


def set_text(values):
    return "{" + list_text(values) + "}"


def units(n):
    return [value for value in range(1, n) if gcd(value, n) == 1]


class CyclicGroupGenerator(ProblemGenerator):
    """
    Cyclic subgroups and generator checks in small modular groups.

    Variants:
    - zn: subgroup generated by a in additive Z_n
    - units: subgroup generated by a in multiplicative U(n)

    Op-codes used:
    - GROUP_SETUP / CYCLIC_START / SUBGROUP_ELEM / CYCLIC_SUBGROUP: trace
    - A / M / MOD_REDUCE (established/shared): modular arithmetic
    - CHECK: generator iff subgroup size equals group size
    - Z: subgroup and generator verdict
    """

    VARIANTS = ["zn", "units"]

    def __init__(self, variant=None):
        if variant is not None and variant not in self.VARIANTS:
            raise ValueError(f"variant must be one of {self.VARIANTS} or None")
        self.variant = variant

    def generate(self) -> dict:
        variant = self.variant or random.choice(self.VARIANTS)
        if variant == "zn":
            problem, steps, answer = self._generate_zn()
        else:
            problem, steps, answer = self._generate_units()
        steps.append(step("Z", answer))
        return dict(
            problem_id=jid(),
            operation=f"cyclic_group_{variant}",
            problem=problem,
            steps=steps,
            final_answer=answer,
        )

    def _generate_zn(self):
        n = random.randint(4, 30)
        element = random.randint(1, n - 1)
        group_size = n
        subgroup = [0]
        current = 0
        steps = [
            step("GROUP_SETUP", f"Z_{n}", "addition mod n",
                 f"group size {group_size}"),
            step("CYCLIC_START", element, "identity 0"),
        ]
        for k in range(1, n + 1):
            previous = current
            total = previous + element
            current = total % n
            steps.append(step("A", previous, element, total))
            steps.append(step("MOD_REDUCE", total, f"mod {n}", current))
            steps.append(step("SUBGROUP_ELEM", f"k={k}", current))
            if current == 0:
                break
            subgroup.append(current)
        is_generator = len(subgroup) == group_size
        verdict = "yes" if is_generator else "no"
        steps.extend([
            step("CYCLIC_SUBGROUP", set_text(subgroup), len(subgroup)),
            step("CHECK", "subgroup size = group size", verdict),
        ])
        answer = f"<{element}> = {set_text(subgroup)}; generator = {verdict}"
        problem = (
            f"Find the cyclic subgroup generated by {element} in Z_{n} "
            f"under addition modulo {n}. Is it a generator of the group?"
        )
        return problem, steps, answer

    def _generate_units(self):
        n = random.choice([8, 10, 12, 14, 15, 16, 18, 20, 21, 22,
                           24, 26, 28, 30])
        elements = units(n)
        element = random.choice([value for value in elements if value != 1])
        group_size = len(elements)
        subgroup = [1]
        current = 1
        steps = [
            step("GROUP_SETUP", f"U({n})", "multiplication mod n",
                 f"group size {group_size}"),
            step("CYCLIC_START", element, "identity 1"),
        ]
        for k in range(1, group_size + 1):
            previous = current
            product = previous * element
            current = product % n
            steps.append(step("M", previous, element, product))
            steps.append(step("MOD_REDUCE", product, f"mod {n}", current))
            steps.append(step("SUBGROUP_ELEM", f"k={k}", current))
            if current == 1:
                break
            subgroup.append(current)
        is_generator = len(subgroup) == group_size
        verdict = "yes" if is_generator else "no"
        steps.extend([
            step("CYCLIC_SUBGROUP", set_text(subgroup), len(subgroup)),
            step("CHECK", "subgroup size = group size", verdict),
        ])
        answer = f"<{element}> = {set_text(subgroup)}; generator = {verdict}"
        problem = (
            f"Find the cyclic subgroup generated by {element} in U({n}) "
            f"under multiplication modulo {n}. Is it a generator of the "
            f"group?"
        )
        return problem, steps, answer
